project:
  type: website
  output-dir: docs
  render:
    - course_intro.qmd
    - reproducible_docs.qmd
    - reproducible_workflows.qmd
    - exercise_reproducibility.qmd
    - OS_2024/dataHandling/dataHandling.qmd
    - OS_2024/Systematic_Reviews/Systematic_Reviews.qmd
    - OS_2024/Systematic_Reviews/meta_analysis.qmd
    - functions.qmd
    - OS_2024/introduction_os/Gentle_introduction_OS_2024.qmd
    - OS_2024/Tools_approaches/Tools_Approaches_OS_2024.qmd

format:
  revealjs:
      highlight-style: a11y
      theme: simple
      code-link: true

execute:
  freeze: auto

website:
    favicon: figures/favicon.ico
